### ISSUE TITLE
Descartar personajes

### ISSUE THREAD

**Issue by UnTalRubi** [UnTalRubi/quien-es-quien#3]
### ¿Quién?

El jugador.

### ¿Qué quiere hacer?

Eliminar personajes que no son el suyo.

### ¿Para qué?

Para saber los personajes que pueden ser el suyo.

-----------------------------

## Criterios de aceptación

- Se eliminan o tapan personajes.
- Los personajes descartados no son el del jugador.
- Los personajes se descartan en función de las características.
- Las características son definidas por el jugador.

**Comment by avedado** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?3C41DE1649389F696CE99F9612E8867D92A9
